// 房間基本資訊配置
export const ROOM_META = {
  room1: {
    title: '台南仁德・陽光景觀雙人套房',
    address: '台南市仁德區',
    price: '$11,000 / 月',
    size: '6.5坪',
    layout: '1房 1衛',
    floor: '3F/4F',
    desc: '雙人套房、落地窗陽台、乾溼分離衛浴、全新家具與電器設備。',
    agentName: '許先生',
    agentRole: '房東直租',
    agentGender: 'male', 
  },
  room2: {
    title: '台南仁德・陽光景觀單人套房',
    address: '台南市仁德區',
    price: '$8,500 / 月',
    size: '4.5坪',
    layout: '1房 1衛',
    floor: '3F/4F',
    desc: '單人套房、落地窗陽台、乾溼分離衛浴、全新家具與電器設備。',
    agentName: '許先生',
    agentRole: '房東直租',
    agentGender: 'male', 
  },
  room3: {
    title: '大安區・靜巷質感宅',
    address: '台北市大安區信義路三段',
    price: '$40,000 / 月',
    size: '18 坪',
    layout: '2 房 2 廳',
    floor: '5F/7F',
    desc: '靜巷低噪音，精緻裝潢，附全套家具家電。',
    agentName: '王經理',
    agentRole: '專業仲介',
  },
  room4: {
    title: '高雄新興區・市區景觀房',
    address: '高雄新興區',
    price: '$24,000 / 月',
    size: '25 坪',
    layout: '2房 1廳 2衛',
    floor: '7F/15F',
    desc: '全新家具與電器設備，靠近市區高雄火車站，附近機能佳。',
    agentName: '洪先生',
    agentRole: '房東直租',
    agentGender: 'male', 
  },
};
